#ifndef DEVELOPMENT_CARD_H
#define DEVELOPMENT_CARD_H

enum DevelopmentCardType {
    DEVELOPMENT_CARD_KNIGHT,
    DEVELOPMENT_CARD_VICTORY_POINT,
    DEVELOPMENT_CARD_ROAD_BUILDING,
    DEVELOPMENT_CARD_YEAR_OF_PLENTY,
    DEVELOPMENT_CARD_MONOPOLY,
    DEVELOPMENT_CARD_COUNT
};

#define DEVELOPMENT_DECK_SIZE 25

#endif
